### ISSUE TITLE
How to also move the workspace switcher popup?

### ISSUE THREAD

**Issue by GithubUser699** [Maestroschan/Move-OSD-Windows-GNOME-Extension#2]
I searched and tried for hours now, but don't have much knowledge in js.
I managed to change the size, the color, transparency etc (based on [this link](https://askubuntu.com/questions/1108686/move-modify-workspace-switcher-popup)) but I also would like to move the whole popup to the right.
I tried things like `x = 50;` `WorkspaceSwitcherPopup.set_align` and also tried a whole bunch of things which I combined from different sources and extensions.
I am using GNOME 3.30.2, Debian 10 (Buster) if that's important.

I don't need you to code it, but a hint (like a variable I have to set or what component I have to use) or a tutorial/reference would be great!
I don't quite understand, what exactly I have to add to your code to accomplish my goal – besides: Isn't the gschemas.compiled file a problem for me, if I cannot edit it? Maybe I would have to add something to make it work, but I really don't know...

I hope you can help.
Thank you!

PS: You can see a picture describing what I mean in the 3rd comment [here](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/792).

**Comment by maoschanz** [comment]
first of all LMFAO i'm very dumb this repo has the files of the wrong project, wtf, could you give me the link to the extension.gnome.org page so i can re-download my own code please? 😭😭 i did this a long time ago i can't answer without first looking into it a little 

then the compiled gschema can't be edited because they're compiled, that's the very concept lol, you're supposed to edit the XML file and run `glib-compile-schemas ./schemas` at the root of the project to regenerate the compiled version

**Comment by GithubUser699** [comment]
I know this extension is a bit older, but it does what it's supposed to do.
Here's the link: https://extensions.gnome.org/extension/1220/move-osd-windows/

I think I actually tried to recompile, but it didn't work. I'm not sure though and will retry if I have to edit this file to archieve my goal.
Thank you for your time!

**Comment by GithubUser699** [comment]
@hajdbo forked it and offers it here: https://extensions.gnome.org/extension/1345/better-osd/

Maybe he has an idea?

**Comment by maoschanz** [comment]
> I know this extension is a bit older, but it does what it's supposed to do.
> Here's the link: https://extensions.gnome.org/extension/1220/move-osd-windows/
> 
> I think I actually tried to recompile, but it didn't work. I'm not sure though and will retry if I have to edit this file to archieve my goal.
> Thank you for your time!

ok thanks i fixed my mistake the code on the repo is the correct one now

----

Back to your question:

![Capture d’écran de 2021-07-11 19-41-42](https://user-images.githubusercontent.com/19996113/125204968-2470de00-e280-11eb-96a9-fdc9c1eaf04a.png)

this works (with the same behavior as mine: the number you set are percentages relative to the center of the monitor). You should then figure out how to do the `disable` function

of course if you want to do your own proper extension, you shouldn't just edit my code which is in your .local/share/gnome-shell, you should fork the entire repo to get all the handy scripts to manage the project, and rename files, translation domain, metadata etc. to get `move-workspace-switcher-popup`/`move-workspace-switcher-popup@githubuser699.github.com` as your ids instead (or anything else you prefer, my point is you should just avoid conflicts regarding the translations and the gschemas for example: there can be only one move-osd-windows)

edit: there are also conflicts regarding the name of the class defining the preferences window for some reason. Good luck!

**Comment by GithubUser699** [comment]
Thanks for your efforts so far!
1) So I did the changes you did in that picture.
2) I opened my terminal and ran: `journalctl -f`
3) I restarted my session (opened command dialog, then entered `r`) and looked inside the entries my terminal would display (none where related to the modified move osd windows extension, even when I change settings or turn the extension on/off. Should mean: No errors while running the application)
4) I opened lookingglass using `lg` in the command dialog.
5) Clicked on "extensions" on the top right corner and chose "show errors" from the modified move osd windows extension -> got message, that no errors could be found.

**However** that popup won't move nor disappear, no matter what...

Any idea about it?

**Comment by maoschanz** [comment]
you may want to add `log(h_percent); log(this); log(this.translation_x);` around the end of the else, to check with your terminal what's going on

log whatever you want, it's not a very efficient way to debug, but at least it helps to understand what's wrong

**Comment by GithubUser699** [comment]
My terminal actually shows nothing of it.
But if I go to lookingglas (`lg`) and type something like `log("hello");` the very same terminal shows that log.
Does that mean the extension (or its function) isn't loaded correctly?

**Comment by maoschanz** [comment]
yes, it's not loading the right code. I see you forked it: when you rename something, you have to rename it everywhere so it's consistent

in your fork i see that you did an incomplete copy (?) of the folder instead of just renaming it, and the scripts at the project root still all use my id: it's installing the folder named with my id, and the files i can see don't really make sense anyway

**Comment by GithubUser699** [comment]
Yeah, I'm working on the fork.
But I actually did the changes to your extension locally without changing the id – that's still valid though, since it worked before I changed 'OSDWindow' to 'WorkspaceSwitcherPopup' and the rest of things you had on your picture.

I inserted a few logs now and got following results:

The log I inserted right after the enable() function is printed into the journal/terminal. The 2nd log right after the `let settings = Convenience.getSettings('org.gnome.shell.extensions.move-osd-windows');` works great too. But the 3rd log after `function()` and every other log won't be printed into the terminal – which means it won't be read for some reason, right?

**Comment by maoschanz** [comment]
this 3rd log should be called when switching workspace, not at initialization; if it's not logged when you go to an other workspace, then it would be really more simple if i could see and test what you're programming.

----

you have to rename:

- the folder
- the id in metadata.json
- the name of the extension in metadata.json
- the id in `install.sh` and other bash scripts if you want to use them

then:

- the translation files (.po and .mo files)
- the translation domain in `prefs.js`

and for the settings:

- the gschema file
- and the ids in its content
- don't forget to recompile it
- the parameter given to `Convenience.getSettings` in extension.js' line 40

finally, the name of the class `OSDSettingsWidget` in prefs.js

----

Once this is properly renamed, you shouldn't have a single occurrence of "move-osd-windows" in the entire project. Then you commit and push it, and i will be able to test what you did without conflicts, and help you find if something's not right

**Comment by GithubUser699** [comment]
Okay. I'll change it and tag you here (@maoschanz) after I finished.
I did change the workspaces, but nothing happend.
Thank you for the great help!

**Comment by GithubUser699** [comment]
do I have to edit line 16/17 of prefs.js too (and where do I know what to put into it)?

**Comment by GithubUser699** [comment]
~So, now I somehow cannot see my extension in tweaks at all...
I must have done something wrong somehow while I edited the files in my repository. I'll try to solve this tomorrow.~

**Comment by maoschanz** [comment]
it doesn't appear because you haven't renamed the gschema.xml file, and it doesn't work because you didn't change the line 43 of my screenshot

also, if the switch to hide the popup doesn't work (i haven't tried), it might be because 3.30 is a damn old version and you need to re-add the ".actor" which are on the screenshot but which i removed from the code before your fork it

**Comment by GithubUser699** [comment]
You're right, I didn't rename it, but did that offline on my machine yesterday (I'm going to upload it now).
The reason it didn't appear was another one though: I forgot the `,` in metadata.json right after shell version 3.30.

3.30 is the most recent version for debian stable, which is using older software than most other linux distros, that's right. Where do I have to add the ".actor"?

**Comment by maoschanz** [comment]
oh sorry they're not in the screenshot, i thought they were

they should be before the 2 ".visible", but again it's only if the switch doesn't work. If it works, the code can stay the same

**Comment by GithubUser699** [comment]
The switch indeed isn't working. If you go to [my fork to the extension.js](https://github.com/GithubUser699/Move-workspaceSwitcherPopup-GNOME-Extension/blob/0487617b20ac73633ea9bdb13a3c5c88190d3801/move-workspaceSwitcherPopup@GithubUser699.github.com/extension.js) it only works until line 45. 
No matter if I set `this.visible = false` or `this.actor.visible = false` (same with 'true') the code won't work for some reasons.
The log(); part isn't called too.

**Comment by GithubUser699** [comment]
Maybe something isn't working with the injections part?
It works with your version (with the osd windows) but maybe this isn't supported for the workspaceSwitcherPopup?

**Comment by maoschanz** [comment]
idk what you mean, it works perfectly

**Comment by GithubUser699** [comment]
You mean you downloaded my fork, installed it and it worked?
It doesn't work for me...

**Comment by GithubUser699** [comment]
Since you said it works on your end, I tried another OS:
Fedora 34, GNOME 40.0.0

I had to add version 40 to the metadata, but then it worked. But it doesn't work for my Debian 10, GNOME 3.30.2.

Screenshots from Fedora:
**Before extension**
![BeforeExtension](https://user-images.githubusercontent.com/74927253/125315169-5dfc2480-e326-11eb-97d9-2b8d9c1b3c02.png)

**After extension**
![AfterExtension](https://user-images.githubusercontent.com/74927253/125315271-79672f80-e326-11eb-8e0b-6b49549e97c6.png)

**Comment by maoschanz** [comment]
if "show" isn't a function that existed in version 3.30, you can try to inject in "_redisplay" instead

**Comment by GithubUser699** [comment]
Jep, tried it – doesn't work either.
But there are good news: Debian 11 with GNOME 3.38.5 is soon to be released as a stable version. I already downloaded the live boot (current not-yet stable release) and tried, if this fork works there.
And well, it did! I only testet whether it works with moving the popup if I manually set values into the extension.js, so settings might not work yet. But since Debian 11 will be released very soon, I think I'll give up on this project for 3.30.2 and build it for 3.38.5 instead.
I guess this issue can be closed.

Thank you for all of your help maoschanz!

PS: How do you know what you have to inject? Do you look at some documentation for that or where can I look these things up?
I know there is the source code available for GNOME, but it's the source code for the newest release as far as I can tell.

**Comment by maoschanz** [comment]
>PS: How do you know what you have to inject? Do you look at some documentation for that or where can I look these things up?

No, you have to read the code https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/ui/workspaceSwitcherPopup.js#L122

based on former versions of the code, i think it's maybe "_show" with an underscore, although you're right it's simpler to just wait a few months to get the next debian. Or you can use Sid, it's fine for a daily desktop use.
